In [1]:
# Import the NumPy package
import numpy as np

The fundamental type used by NumPy is the numpy array

In [6]:
x = np.array([12, 3, 6, 14])
print(x)

[12  3  6 14]


In [7]:
# Indicies start at 0!
x[1]

3

In [8]:
# Find the length of x
len(x)

4

In [9]:
# Find the dimensions
x.shape

(4,)

In [11]:
# Matrices are 2-D numpy arrays
A = np.array([[5, 78, 2, 38, 0],
              [6, 79, 3, 35, 1],
              [7, 80, 4, 36, 21]])

In [12]:
print(A)

[[ 5 78  2 38  0]
 [ 6 79  3 35  1]
 [ 7 80  4 36 21]]


In [14]:
A.shape

(3, 5)

In [17]:
# NumPY also supports random vectors and matrices 
x = np.random.rand(4)
print(x)

[0.72817585 0.52652038 0.40305578 0.94882436]


In [19]:
A = np.random.rand(10, 4)
print(A)

[[0.18563186 0.79036229 0.61364486 0.60869156]
 [0.66441528 0.45920012 0.85969103 0.9765878 ]
 [0.76129857 0.32669153 0.81413236 0.51494385]
 [0.16721523 0.63300943 0.71292529 0.9547418 ]
 [0.88699471 0.07865154 0.53895812 0.73771608]
 [0.36183053 0.09286325 0.3501037  0.86772532]
 [0.60724025 0.89609528 0.9097641  0.59034711]
 [0.47488939 0.07488651 0.70087695 0.18675008]
 [0.39434587 0.70597769 0.31276908 0.23359982]
 [0.83863126 0.1225889  0.19199628 0.02620194]]


In [20]:
# Vector products use the "@" symbol
A @ x

array([1.37618897, 1.99870312, 1.543101  , 1.6482854 , 1.60449294,
       1.27680089, 1.84081152, 0.84491779, 1.00657337, 0.77746283])

In [24]:
# Transpose can be a little messy 
np.transpose(A)

array([[0.18563186, 0.66441528, 0.76129857, 0.16721523, 0.88699471,
        0.36183053, 0.60724025, 0.47488939, 0.39434587, 0.83863126],
       [0.79036229, 0.45920012, 0.32669153, 0.63300943, 0.07865154,
        0.09286325, 0.89609528, 0.07488651, 0.70597769, 0.1225889 ],
       [0.61364486, 0.85969103, 0.81413236, 0.71292529, 0.53895812,
        0.3501037 , 0.9097641 , 0.70087695, 0.31276908, 0.19199628],
       [0.60869156, 0.9765878 , 0.51494385, 0.9547418 , 0.73771608,
        0.86772532, 0.59034711, 0.18675008, 0.23359982, 0.02620194]])

In [35]:
A.ndim

2