In [1]:
using LinearAlgebra
A = [2 1 1 0.0; 4 3 3 1; 8 7 9 5; 6 7 9 8]

4×4 Array{Float64,2}:
 2.0  1.0  1.0  0.0
 4.0  3.0  3.0  1.0
 8.0  7.0  9.0  5.0
 6.0  7.0  9.0  8.0

In [2]:
function Id(n)
    Id = zeros(n,n)
    for i = 1:n
        Id[i,i] = 1.0
    end
    return Id
end

Id (generic function with 1 method)

In [3]:
function LU(A)
    m = size(A)[1]
    U = copy(A)
    L = Id(m)
    
    for k = 1:m-1
        for j = k+1:m
            L[j,k] = U[j,k]/U[k,k]
            U[j,k:m] = U[j,k:m] - L[j,k]*U[k,k:m]
        end
    end 
    
    return L, U
end

LU (generic function with 1 method)

In [4]:
L, U = LU(A)

([1.0 0.0 0.0 0.0; 2.0 1.0 0.0 0.0; 4.0 3.0 1.0 0.0; 3.0 4.0 1.0 1.0], [2.0 1.0 1.0 0.0; 0.0 1.0 1.0 1.0; 0.0 0.0 2.0 2.0; 0.0 0.0 0.0 2.0])

In [5]:
L

4×4 Array{Float64,2}:
 1.0  0.0  0.0  0.0
 2.0  1.0  0.0  0.0
 4.0  3.0  1.0  0.0
 3.0  4.0  1.0  1.0

In [6]:
U

4×4 Array{Float64,2}:
 2.0  1.0  1.0  0.0
 0.0  1.0  1.0  1.0
 0.0  0.0  2.0  2.0
 0.0  0.0  0.0  2.0

In [7]:
A

4×4 Array{Float64,2}:
 2.0  1.0  1.0  0.0
 4.0  3.0  3.0  1.0
 8.0  7.0  9.0  5.0
 6.0  7.0  9.0  8.0

In [8]:
norm(A - L*U)

0.0

In [9]:
function forward_solve(L, b)
    m = size(L)[1]
    c = zeros(m)
    c[1] = b[1]/L[1,1]
    
    for k = 2:m
        c[k] = (b[k] - (sum([L[k,i]*c[i] for i = 1:k-1])))/L[k,k]
    end
    
    return c
end

        

forward_solve (generic function with 1 method)

In [10]:
function back_solve(U,b)
    m = size(U)[1]
    x = zeros(m)
    x[m] = b[m]/U[m,m]
    
    for k = m-1:-1:1
        x[k] = (b[k] - (sum([U[k,i]*x[i] for i = k+1:m])))/U[k,k]
    end
    
    return x
end    

back_solve (generic function with 1 method)

In [11]:
function solve_system(A,b)
    L,U = LU(A)
    c = forward_solve(L,b)
    x = back_solve(U,c)
    return x
end


solve_system (generic function with 1 method)

In [13]:
A = rand(1000, 1000)
b = rand(1000);

In [14]:
x0 = solve_system(A,b)

1000-element Array{Float64,1}:
 -1.0810366609249664 
 -0.2221433516438385 
  0.6129398841078271 
  0.8865206534449267 
  1.4738159392935553 
 -5.3752038211477045 
 -1.0316680820800177 
 -1.1554136034332727 
 -0.17369209401816638
 -2.095905852446741  
 -2.433155373803495  
 -1.8338148232529852 
  0.25476689856920154
  ⋮                  
 -1.574562070221605  
 -0.6219362611931326 
 -0.4341445066067153 
  1.6219798580657003 
 -0.6023878522967444 
  0.9900054987818439 
 -0.8834751642448773 
  1.8805364155557407 
  0.47779042686851975
  1.0186295046646645 
 -1.117435228533178  
 -0.909307526172637  

In [15]:
x1 = A\b

1000-element Array{Float64,1}:
 -1.081036660852017  
 -0.2221433516664555 
  0.6129398840220908 
  0.8865206534283047 
  1.4738159391357537 
 -5.3752038206983555 
 -1.0316680819850117 
 -1.1554136032486615 
 -0.17369209407073072
 -2.0959058522551053 
 -2.4331553735505276 
 -1.8338148231907578 
  0.2547668985627581 
  ⋮                  
 -1.5745620701264933 
 -0.6219362611777999 
 -0.4341445065199248 
  1.621979857952328  
 -0.6023878522224662 
  0.9900054986622004 
 -0.8834751641542521 
  1.8805364153537811 
  0.47779042686600254
  1.0186295045826241 
 -1.1174352284298352 
 -0.9093075261564023 

In [16]:
norm(x0 - x1)

4.421595827727972e-9

In [19]:
A = rand(10000, 10000)
b = rand(10000)

10000-element Array{Float64,1}:
 0.6265892205726846  
 0.9146557091743297  
 0.6142949741386707  
 0.12953370245260887 
 0.44600760299293585 
 0.006371931298176925
 0.5653273265881993  
 0.23900079530802132 
 0.760543112018381   
 0.14631941338494103 
 0.006370844350734872
 0.03032815343996731 
 0.7624345929369936  
 ⋮                   
 0.582915165256634   
 0.306272721875553   
 0.12987348124364773 
 0.11666605914151584 
 0.487256294870674   
 0.9193698376202364  
 0.2564882233175809  
 0.39100712190434694 
 0.34898515618737336 
 0.44607963080735225 
 0.6111626558495529  
 0.3863720925946843  

In [20]:
x0 = solve_system(A,b)

InterruptException: InterruptException: