In [1]:
using LinearAlgebra
A = [2 1 1 0.0; 4 3 3 1; 8 7 9 5; 6 7 9 8]

4×4 Array{Float64,2}:
 2.0  1.0  1.0  0.0
 4.0  3.0  3.0  1.0
 8.0  7.0  9.0  5.0
 6.0  7.0  9.0  8.0

In [2]:
function Id(n)
    Id = zeros(n,n)
    for i = 1:n
        Id[i,i] = 1.0
    end
    return Id
end

Id (generic function with 1 method)

In [3]:
function LU!(A)
    m = size(A)[1]
    U = A
    L = Id(m)
    
    for k = 1:m-1
        for j = k+1:m
            L[j,k] = U[j,k]/U[k,k]
            U[j,k:m] = U[j,k:m] - L[j,k]*U[k,k:m]
        end
    end 
    
    return L, U
end

LU (generic function with 1 method)

In [4]:
L, U = LU(A)

([1.0 0.0 0.0 0.0; 2.0 1.0 0.0 0.0; 4.0 3.0 1.0 0.0; 3.0 4.0 1.0 1.0], [2.0 1.0 1.0 0.0; 0.0 1.0 1.0 1.0; 0.0 0.0 2.0 2.0; 0.0 0.0 0.0 2.0])

In [5]:
L

4×4 Array{Float64,2}:
 1.0  0.0  0.0  0.0
 2.0  1.0  0.0  0.0
 4.0  3.0  1.0  0.0
 3.0  4.0  1.0  1.0

In [6]:
U

4×4 Array{Float64,2}:
 2.0  1.0  1.0  0.0
 0.0  1.0  1.0  1.0
 0.0  0.0  2.0  2.0
 0.0  0.0  0.0  2.0

In [8]:
L*U

4×4 Array{Float64,2}:
 2.0  1.0  1.0  0.0
 4.0  3.0  3.0  1.0
 8.0  7.0  9.0  5.0
 6.0  7.0  9.0  8.0

In [9]:
A

4×4 Array{Float64,2}:
 2.0  1.0  1.0  0.0
 0.0  1.0  1.0  1.0
 0.0  0.0  2.0  2.0
 0.0  0.0  0.0  2.0